---
- name: Apply grafana Quadlet
  ansible.builtin.include_role:
    name: quadlet
    tasks_from: service
  vars:
    quadlet_name: grafana
- name: Apply grafana configuration changes
  ansible.builtin.meta: flush_handlers
