---
- name: install runner
  ansible.builtin.import_tasks: install.yml
  tags: [install]
- name: configure runner
  ansible.builtin.import_tasks: configure.yml
  tags: [configure]
- name: service runner
  ansible.builtin.import_tasks: service.yml
  tags: [service]
- name: verify runner
  ansible.builtin.import_tasks: verify.yml
  tags: [verify]
