---
- name: Install chrony
  ansible.builtin.import_tasks: install.yml
  tags: [install]
- name: Configure chrony
  ansible.builtin.import_tasks: configure.yml
  tags: [configure]
- name: Service chrony
  ansible.builtin.import_tasks: service.yml
  tags: [service]
- name: Verify chrony
  ansible.builtin.import_tasks: verify.yml
  tags: [verify]
