---
lldap_image: docker.io/lldap/lldap@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
lldap_uid: 992
lldap_gid: 992
lldap_base_dn: dc=infrabox,dc=internal
lldap_admin_username: svc-identity-admin
lldap_reader_username: svc-ldap-reader
lldap_management_http_port: 17170
lldap_management_ldaps_port: 16360
